### ISSUE TITLE
Project will not load with extensions on http site

### ISSUE THREAD

**Issue by pooiod** [PenguinMod/PenguinMod-ExtensionsGallery#217]
When loading a project via the Runtime extension, I noticed that it wouldn't load any projects that use extensions. I tested this with other sites and found that the issue only happens on http sites.

I have attached the following video below as an example
https://github.com/user-attachments/assets/abcdbd99-ea45-4092-88ce-bcd2883e2e67

**Comment by TheShovel** [comment]
this is not an extension issue, this is just how browser security works. Http is not secure. You should really just use https 

_If a website uses HTTP instead of HTTPS, all requests and responses can be read by anyone who is monitoring the session. Essentially, a malicious actor can just read the text in the request or the response and know exactly what information someone is asking for, sending, or receiving._ - Cloudflare
